config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  get 'books' => 'books#index'
  post 'books' =>'books#create'
  get 'books/:id' => 'books#show', as: 'book'
  get 'books/:id/edit' => 'books#edit', as: 'edit_books'
  patch 'books/:id' => 'books#update', as: 'update_books'
  delete 'books/:id' => 'books#destroy', as: 'destroy_books'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @book = Book.new
    @books = Book.all
  end
  
  def show
     @book = Book.find(params[:id])
  end
  
  def create
    book = Book.new(book_params)
    if book.save
      redirect_to "/books/#{book.id}",notice:'Book was successfully created.'
    else
      render :index
    end
  end
  
  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    book = Book.find(params[:id])
    if book.update(book_params) 
      redirect_to "/books/#{book.id}",notice:'Book was successfully created.'
    else
      render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to "/books"
  end
  
  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
 <h1 class="title">Editing Book</h1>

    <%= form_with model:@book, local: true do |f| %>
      <% if @book.errors.any? %>
      <div class = "alert"><%= @book.errors.count %> error prohibited this book from being saved:
       <ul>
          <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
    
    <div class = "item">
        <h4>Title</h4>
        <%= f.text_field :title %>
    </div>
    <div class= "item">
        <h4>Body</h4>
        <%= f.text_area :body %>
    </div>
    <div class= "item">
        <%= f.submit 'Update Book' %>
    </div>
    <% end %>
</div>
<div class = "nav">
    <div class = "nav1"><%= link_to "Show", "/books/#{@book.id}" %></div>
    <div class = "nav2"><%= link_to "Back", "/books" %></div>
</div>
   

app/views/books/index.html.erb
<h1 class="title">Books</h1>

<main>
  <table>
    <thead>
      <tr>
        <th class = "a">Title</th>
        <th class = "b">Body</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
       <tr>
         <td><%= book.title %></td>
         <td><%= book.body %></td>
         <td><%= link_to "Show", book_path(book.id) %></td>
         <td><%= link_to "Edit", edit_books_path(book.id) %></td>
         <td><%= link_to "Destroy", destroy_books_path(book.id) , method: :delete, "data-confirm" => "本当に削除しますか？" %>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>

<div class="sub-title">New book</div>

<%= form_with model:@book, local:true do |f| %>
    
<div class = "item">
  <h5>Title</h5>
  <%= f.text_field :title %>
</div>
<div class = "item">
  <h5>Body</h5>
  <%= f.text_area :body %>
</div>
<div class = "item">
  <%= f.submit 'Create Book' %>
</div>
<% end %>

app/views/books/show.html.erb
<h1 class="title"></h1>
<div class = "notice"><%= notice %></div>

<div class ="show-item">
  <b>Title：</b><%= @book.title %>
</div>

<div class ="show-item">
  <b>Body : </b><%= @book.body %>
</div>

<div class = "nav">
    <div class = "nav1"><%= link_to "Edit", edit_books_path(@book.id) %></div>
    <div class = "nav2"><%= link_to "Back", "/books" %></div>
</div>

app/views/homes/top.html.erb
<h1 class="title">ようこそ Bookers へ！</h1>

  <div class="top">
    Bookersでは、さまざまな書籍に関するあなたの意見や　<br>
    印象を共有することができます</p>
  </div>

<div class ="top-url">
  <a href="/books">start</a>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= yield %>
  </body>
</html>